name: docker-publish

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: apache/rocketmq


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        #if: env.exists == 'false' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
